output "secret_arns" {
  description = "The ARN values of the generated secrets"
  value       = {
    for k, v in aws_secretsmanager_secret.this : k => v.arn
  }
}

output "secrets" {
  description = "Returns all secrets generated by the secrets manager module"
  sensitive   = true
  value       = {
    for k, v in aws_secretsmanager_secret_version.this : k => v.secret_string
  }
}

output "names" {
  value       = var.names
  description = "Returns list of secret names to be created."
}

output "path" {
  value       = var.path
  description = "Path to secret values"
}

output "secret_iam_policy_doc_json" {
  value       = data.aws_iam_policy_document.resource_policy_MA.json
  description = "JSON doc of the policy output to use on roles if desired"
}